name: nostr_signaling_test
version: 0.1.0
description: Test package for Nostr Signaling library
publish_to: none

environment:
  sdk: '^3.11.0'

resolution: workspace

dependencies:
  mockito: ^5.4.0
  nostr_signaling:
    path: ../nostr_signaling
  singleton_manager: ^0.6.1
  test: ^1.24.0

dev_dependencies:
  dart_nostr: any
  lints: ^4.0.0
