name: nostr_signaling
version: 0.1.0
description: Nostr signaling library with data compression support

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  archive: ^3.4.0
  dart_nostr: ^10.0.1
  convert: ^3.1.0

dev_dependencies:
  test: ^1.31.1
  lints: ^2.1.0
